// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARdFmJQBWyF6Iby14Rif-DBHmWlsWDDCc',
    appId: '1:592252446295:web:d4ea0b9845131cdc532512',
    messagingSenderId: '592252446295',
    projectId: 'airsoft-14d94',
    authDomain: 'airsoft-14d94.firebaseapp.com',
    storageBucket: 'airsoft-14d94.appspot.com',
    measurementId: 'G-PTT265Z6MC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNlsls40qMA28vbzFg7AUxRDhEn-EiLUw',
    appId: '1:592252446295:android:8645df57202352bd532512',
    messagingSenderId: '592252446295',
    projectId: 'airsoft-14d94',
    storageBucket: 'airsoft-14d94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGSsngiQS8oyb6AK2zU3_czotO_ZAtzCQ',
    appId: '1:592252446295:ios:4830ef68d473b1ae532512',
    messagingSenderId: '592252446295',
    projectId: 'airsoft-14d94',
    storageBucket: 'airsoft-14d94.appspot.com',
    iosClientId: '592252446295-0dc5icjiofeqcdojjh8frts840lh6ubv.apps.googleusercontent.com',
    iosBundleId: 'com.example.airsoft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGSsngiQS8oyb6AK2zU3_czotO_ZAtzCQ',
    appId: '1:592252446295:ios:c619132be036c384532512',
    messagingSenderId: '592252446295',
    projectId: 'airsoft-14d94',
    storageBucket: 'airsoft-14d94.appspot.com',
    iosClientId: '592252446295-df5fvad1782ero3l3pik0ob8s6ja4rci.apps.googleusercontent.com',
    iosBundleId: 'com.example.airsoft.RunnerTests',
  );
}
